import * as CFG from './config.js';import { requireAuth, logout as doLogout } from './auth.js';
requireAuth();
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s)),esc=s=>(s==null?'':String(s)).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c])),fmtTime=t=>{try{return new Date(t).toLocaleString()}catch{return String(t||'')}};const to10=v=>Number(v)?1:0;
function rowLoading(c){return `<tr><td colspan="${c}" class="center muted">Memuat…</td></tr>`}function rowEmpty(c){return `<tr><td colspan="${c}" class="center muted">Belum ada data</td></tr>`}
const pages={home:$('#home-page'),v1:$('#v1-page'),v2:$('#v2-page'),logs:$('#logs-page')};const title=$('#page-title');
function switchPage(p){Object.entries(pages).forEach(([k,el])=>el?.toggleAttribute('hidden',k!==p));$$('.sidebar a').forEach(a=>a.classList.toggle('active',a.dataset.page===p));if(title)title.textContent=(p==='home'?'Home':p.toUpperCase())}
$$('.sidebar a').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();const p=a.dataset.page;if(!p)return;switchPage(p);if(p==='v1')loadV1();if(p==='v2')loadV2();if(p==='logs')loadLogs()}));switchPage('home');
const URL_V1=CFG.SHEET_API_URL_V1||(CFG.SHEET_API_URL?CFG.SHEET_API_URL+'?sheet=v1':'');const URL_V2=CFG.SHEET_API_URL_V2||(CFG.SHEET_API_URL?CFG.SHEET_API_URL+'?sheet=v2':'');const URL_LOGS=(CFG.SHEET_API_URL?(CFG.SHEET_API_URL+'?action=logs'):'');function withToken(u){if(!CFG.SHEET_TOKEN)return u;return u+(u.includes('?')?'&':'?')+'token='+encodeURIComponent(CFG.SHEET_TOKEN)}
async function httpJson(url,{method='GET',body}={}){const headers={'Content-Type':'application/json'};if(CFG.SHEET_TOKEN)headers['Authorization']='Bearer '+CFG.SHEET_TOKEN;const res=await fetch(url,{method,headers,body:body?JSON.stringify(body):undefined});if(!res.ok){const txt=await res.text().catch(()=>'' );throw new Error(`HTTP ${res.status} ${txt}`)}const ct=res.headers.get('content-type')||'';if(!ct.includes('application/json')){const txt=await res.text();try{return JSON.parse(txt)}catch{return txt}}return res.json()}
const Provider={async listV1(){if(String(CFG.DATA_PROVIDER).toLowerCase()==='sheet'){const url=withToken(URL_V1+(URL_V1.includes('?')?'&':'?')+'action=list');return httpJson(url)}throw new Error('Provider belum diimplementasi: '+CFG.DATA_PROVIDER)},async listV2(){if(String(CFG.DATA_PROVIDER).toLowerCase()==='sheet'){const url=withToken(URL_V2+(URL_V2.includes('?')?'&':'?')+'action=list');return httpJson(url)}throw new Error('Provider belum diimplementasi: '+CFG.DATA_PROVIDER)},async listLogs(){if(String(CFG.DATA_PROVIDER).toLowerCase()==='sheet'){if(!URL_LOGS)return [];const url=withToken(URL_LOGS);return httpJson(url)}return []},async createV1(row){if(String(CFG.DATA_PROVIDER).toLowerCase()==='sheet'){const url=withToken(URL_V1);return httpJson(url,{method:'POST',body:{action:'create',row}})}throw new Error('Provider belum diimplementasi: '+CFG.DATA_PROVIDER)},async createV2(row){if(String(CFG.DATA_PROVIDER).toLowerCase()==='sheet'){const url=withToken(URL_V2);return httpJson(url,{method:'POST',body:{action:'create',row}})}throw new Error('Provider belum diimplementasi: '+CFG.DATA_PROVIDER)},async deleteV1(user_id){if(String(CFG.DATA_PROVIDER).toLowerCase()==='sheet'){const url=withToken(URL_V1);return httpJson(url,{method:'POST',body:{action:'delete',user_id}})}throw new Error('Provider belum diimplementasi: '+CFG.DATA_PROVIDER)},async deleteV2(user_id){if(String(CFG.DATA_PROVIDER).toLowerCase()==='sheet'){const url=withToken(URL_V2);return httpJson(url,{method:'POST',body:{action:'delete',user_id}})}throw new Error('Provider belum diimplementasi: '+CFG.DATA_PROVIDER)}};
$('#btn-logout')?.addEventListener('click',()=>doLogout());
const dlg=$('#modal'),form=$('#form-create'),fieldUserId=$('#f-userid')||$('#userid')||$('#user_id'),fieldAngka=$('#f-angka')||$('#angka'),fieldFlag=$('#f-flag')||$('#flag'),fieldExtra=$('#f-extra'),wrapV2Nama=$('#wrap-v2-nama')||document.createElement('div'),fieldNamaV2=$('#f-nama-v2')||$('#f-nama')||$('#nama-v2')||document.createElement('input'),createState=$('#create-state')||$('#state-create')||document.createElement('div'),dlgConfirm=$('#confirm')||$('#confirm-dialog')||document.createElement('dialog'),btnYes=$('#btn-yes')||$('#confirm-yes')||document.createElement('button'),btnNo=$('#btn-no')||$('#confirm-no')||document.createElement('button'),confirmText=$('#confirm-text')||$('#confirm-message')||document.createElement('div');
let targetSheet='v1';($('#btn-open-v1')||$('#btn-open-modal'))?.addEventListener('click',()=>openModal('v1'));$('#btn-open-v2')?.addEventListener('click',()=>openModal('v2'));$('#btn-cancel')?.addEventListener('click',()=>dlg?.close());
function openModal(sheet){targetSheet=sheet;createState.textContent='';form?.reset();if(!dlg?.showModal)return;const labelExtra=$('#label-extra');if(labelExtra)labelExtra.textContent=(sheet==='v1')?'Nama (D)':'Kode (D)';if(wrapV2Nama)wrapV2Nama.style.display=(sheet==='v1')?'none':'';dlg.showModal()}
form?.addEventListener('submit',async e=>{e.preventDefault();try{const user_id=(fieldUserId?.value||'').trim();const angka=Number(fieldAngka?.value||0);const flag=to10(fieldFlag?.value||0);if(targetSheet==='v1'){const row={user_id,angka,flag,nama:(fieldExtra?.value||'').trim(),created_at:Date.now()};await Provider.createV1(row);createState.textContent='Berhasil disimpan.';await loadV1()}else{const row={user_id,angka,flag,kode:(fieldExtra?.value||'').trim(),nama:(fieldNamaV2?.value||'').trim(),created_at:Date.now()};await Provider.createV2(row);createState.textContent='Berhasil disimpan.';await loadV2()}setTimeout(()=>dlg?.close?.(),250)}catch(err){console.error(err);createState.textContent=err?.message||'Gagal menyimpan.'}});
const bodyV1=$('#body-v1')||$('#whitelist-body'),bodyV2=$('#body-v2'),bodyLogs=$('#body-logs');
function renderRows(tbody,rows,tpl,cols){if(!tbody)return;if(!rows||rows.length===0){tbody.innerHTML=rowEmpty(cols);return}tbody.innerHTML=rows.map(tpl).join('');tbody.querySelectorAll('.btn-del[data-id]').forEach(btn=>{btn.addEventListener('click',()=>askDelete(btn.dataset.id,btn.dataset.sheet||'v1'))})}
function tplV1(r){const hasDeleteCol=!!document.querySelector('th.th-actions-v1');return `<tr><td>${esc(r.user_id)}</td><td>${esc(r.angka)}</td><td>${to10(r.flag)}</td><td>${esc(r.nama||'')}</td><td>${esc(fmtTime(r.created_at))}</td>${hasDeleteCol?`<td><button class="btn-del" data-id="${esc(r.user_id)}" data-sheet="v1">Hapus</button></td>`:''}</tr>`}
function tplV2(r){const hasDeleteCol=!!document.querySelector('th.th-actions-v2');return `<tr><td>${esc(r.user_id)}</td><td>${esc(r.angka)}</td><td>${to10(r.flag)}</td><td>${esc(r.kode||'')}</td><td>${esc(r.nama||'')}</td>${hasDeleteCol?`<td><button class="btn-del" data-id="${esc(r.user_id)}" data-sheet="v2">Hapus</button></td>`:''}</tr>`}
function tplLog(r){return `<tr><td>${esc(fmtTime(r.ts||r.created_at))}</td><td>${esc(r.actor||'')}</td><td>${esc(r.action||'')}</td><td>${esc(r.sheet||'')}</td><td>${esc(r.user_id||'')}</td><td>${esc(r.nama||'')}</td><td>${esc(r.row||'')}</td></tr>`}
async function loadV1(){if(bodyV1)bodyV1.innerHTML=rowLoading(6);const rows=await Provider.listV1();const cols=document.querySelectorAll('#v1-page thead th').length||6;renderRows(bodyV1,rows,tplV1,cols)}
async function loadV2(){if(bodyV2)bodyV2.innerHTML=rowLoading(6);const rows=await Provider.listV2();const cols=document.querySelectorAll('#v2-page thead th').length||6;renderRows(bodyV2,rows,tplV2,cols)}
async function loadLogs(){if(bodyLogs)bodyLogs.innerHTML=rowLoading(7);const rows=await Provider.listLogs();const cols=document.querySelectorAll('#logs-page thead th').length||7;renderRows(bodyLogs,rows,tplLog,cols)}
($('#btn-reload-v1')||$('#btn-reload'))?.addEventListener('click',loadV1);$('#btn-reload-v2')?.addEventListener('click',loadV2);$('#btn-reload-logs')?.addEventListener('click',loadLogs);
function askDelete(user_id,sheet){if(!dlgConfirm?.showModal){if(confirm(`Hapus data ${user_id} dari ${sheet.toUpperCase()}?`)){(sheet==='v1'?Provider.deleteV1(user_id):Provider.deleteV2(user_id)).then(()=>sheet==='v1'?loadV1():loadV2())}return}confirmText.textContent=`Hapus data ${user_id} dari ${sheet.toUpperCase()}?`;dlgConfirm.showModal();const onNo=()=>{dlgConfirm.close();cleanup()};const onYes=async()=>{try{if(sheet==='v1')await Provider.deleteV1(user_id);else await Provider.deleteV2(user_id);sheet==='v1'?loadV1():loadV2()}finally{dlgConfirm.close();cleanup()}};function cleanup(){btnNo.removeEventListener('click',onNo);btnYes.removeEventListener('click',onYes)}btnNo.addEventListener('click',onNo,{once:true});btnYes.addEventListener('click',onYes,{once:true})}
if(bodyV1)loadV1();
